### ISSUE TITLE
AWS configuration recommendations?

### ISSUE THREAD

**Issue by chrisbsmith** [raffaelespazzoli/openshift-sdn-encrypted-tunnel#6]
Hi @raffaelespazzoli , do you happen to have any AWS configuration recommendations to deploy and configure the SDN tunnel between two VPCs?  I currently have two VPCs with non-overlapping CIDRs running OpenShift v3.11, each other those with non-overlapping network CIDRs too.  

As you're aware, the LoadBalancer configuration is not suitable for AWS since ELBs do not support UDP transport.  And all of our nodes are in private subnets, making the NodePort option less than ideal.  

I've tried to use the [nginx openshift router](https://github.com/nginxinc/nginx-openshift-router) and create [udp routes through nginx](https://github.com/nginxinc/nginx-openshift-router/tree/master/examples/tcp-udp) to allow for UDP traffic into the cluster, but am not having much luck.  While the routes properly route ingress udp traffic, I am still unable to route traffic through the tunnel.

I wanted to see if you had a solution that worked in AWS that I could try and possibly build upon before I continue down this part or look at alternate VPN or MultiCluster solutions. Thanks in advance.

**Comment by raffaelespazzoli** [comment]
with respect to the AWS load balancer not being a L4 load balancer, I think now this is fixed with the new [network load balancer](https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/).
It should be possible to request it with the following service annotation: `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"` , see [here](https://kubernetes.io/docs/concepts/services-networking/service/#network-load-balancer-support-on-aws-alpha)

Also if all you are doing is connecting two cluster in two different AWS zones, assuming that there is proper routing between those zones, you may want to use an internal load balancer. An internal load balancer is typically less expensive (although I don't know the exact price in AWS) because it does not consume and external IP. You can request an internal load balancer with this annotation: `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` , see [here](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer)

Also look [here](https://kubernetes.io/docs/concepts/services-networking/service/#other-elb-annotations) for another bunch of aws-specific annotations that might be useful to your use case.

**Comment by chrisbsmith** [comment]
Thanks for the recommendations.  Unfortunately, it appears that the NLB only supports TCP and TLS. And the ALBs only support HTTP and HTTPS.  

While both of our clusters are now inner-AWS, we are testing for possible future configurations where we may not have all clusters in AWS.  

I'll continue to research other options and will let you know if I make any progress.

**Comment by chrisbsmith** [comment]
While I have not looked into this yet, AWS did announce UDP support for nlbs. https://aws.amazon.com/blogs/aws/new-udp-load-balancing-for-network-load-balancer/
